fullNames={
	"Basic Attenti...":"Basic Attention Token"
	,"High Performa...":"High Performance Blockchain"
	,"Matrix AI Net...":"Matrix AI Network"
	,"Dynamic Tradi...":"Dynamic Tradiing Rights"
	,"Raiden Networ...":"Raiden Network Token"
	,"Santiment Net...":"Santiment Network Token"
	,"Ripio Credit ...":"Ripio Credit Network"
	,"Quantum Resis...":"Quantum Resistant Ledger"
	,"Trinity Netwo...":"Trinity Network Credit"
	,"BlockMason Cr...":"BlockMason Credit Protocol"
	,"IHT Real Esta...":"IHT Real Estate Protocol"
	,"Spectre.ai Di...":"Spectre.ai Dividend Token"
	,"Nimiq Exchang...":"Nimiq Exchange Token"
	,"Safe Exchange...":"Safe Exchange Coin"
	,"Internet Node...":"Internet Node Token"
	,"Republic Prot...":"Republic Protocol"
	,"Moeda Loyalty...":"Moeda Loyalty Points"
	,"Restart Energ...":"Restart Energy MWAT"
	,"Measurable Da...":"Measurable Data Token"
	,"Waves Communi...":"Waves Community Token"
	,"Open Trading ...":"Open Trading Network"
	,"Hi Mutual Soc...":"Hi Mutual Society"
	,"Hackspace Cap...":"Hackspace Capital"
	,"Profile Utili...":"Profile Utility Token"
	,"Circuits of V...":"Circuits of Value"
	,"Guaranteed Et...":"Guaranteed Ethurance Token Extra"
	,"Spectre.ai Ut...":"Spectre.ai Utility Token"
	,"Education Eco...":"Education Ecosystem"
	,"Sharpe Platfo...":"Sharpe Platform Token"
	,"Ethereum Movi...":"Ethereum Movie Venture"
	,"Speed Mining ...":"Speed Mining Service"
	,"Miners' Rewar...":"Miners' Reward Token"
	,"Intelligent T...":"Intelligent Trading Tech"
	,"Billionaire T...":"Billionaire Token"
	,"Useless Ether...":"Useless Ethereum Token"
	,"Royal Kingdom...":"Royal Kingdom Coin"
	,"Commodity Ad ...":"Commodity Ad Network"
	,"Accelerator N...":"Accelerator Network"
	,"DigitalDevelo...":"DigitalDevelopersFund"
	,"Acute Angle C...":"Acute Angle Cloud"
	,"Electronic PK...":"Electronic PK Chain"
	,"Content and A...":"Content and AD Network"
	,"Animation Vis...":"Animation Vision Cash"
	,"Vice Industry...":"Vice Industry Token"
	,"Titanium Bloc...":"Titanium Blockchain"
	,"Lendroid Supp...":"Lendroid Support Token"
	,"CryptopiaFeeS...":"CryptopiaFeeShares"
	,"First Bitcoin...":"First Bitcoin Capital"
	,"United Trader...":"United Traders Token"
	,"President Joh...":"President Johnson"
	,"Internet of T...":"Internet of Things"
	,"GOLD Reward T...":"GOLD Reward Token"
	,"Experience Po...":"Experience Points"
	,"Universal Cur...":"Universal Currency"
	,"Russian Miner...":"Russian Miner Coin"
	,"Internet of P...":"Internet of People"
	,"Interplanetar...":"Interplanetary Broadcast Coin"
	,"Memetic / Pep...":"Memetic / PepeCoin"
	,"Uniform Fisca...":"Uniform Fiscal Object"
	,"Global Curren...":"Global Currency Reserve"
	,"Global Crypto...":"Global Cryptocurrency"
	,"Growers Inter...":"Growers International"
	,"Interstellar ...":"Interstellar Holdings"
	,"Ultimate Secu...":"Ultimate Secure Cash"
	,"Tattoocoin (S...":"Tattoocoin (Standard Edition)"
	,"Philosopher S...":"Philosopher Stones"
	,"Cthulhu Offer...":"Cthulhu Offerings"
	,"Digital Money...":"Digital Money Bits"
	,"Advanced Inte...":"Advanced Intenet Blocks"
	,"Independent M...":"Independent Money System"
	,"Virta Unique ...":"Virta Unique Coin"
	,"Gold Pressed ...":"Gold Pressed Latinum"
	,"CryptoWorldX ...":"CryptoWorldX Token"
	,"Tezos (Pre-La...":"Tezos (Pre-Launch)"
	,"Lightning Bit...":"Lightning Bitcoin [Futures]"
	,"Filecoin [Fut...":"Filecoin [Futures]"
	,"Infinity Econ...":"Infinity Economics"
	,"International...":"International Diamond"
	,"Pabyosi Coin ...":"Pabyosi Coin (Special)"
	,"Tattoocoin (L...":"Tattoocoin (Limited)"
	,"Harvest Maste...":"Harvest Masternode Coin"
	,"UniversalRoya...":"UniversalRoyalCoin"
	,"Digital Bulli...":"Digital Bullion Gold"
	,"Happy Creator...":"Happy Creator Coin"
	,"Advanced Inte...":"Advanced Internet Blocks"
	,"Dynamic Tradi...":"Dynamic Trading Rights"
	//,"EncryptoTel [...":"EncryptoTel [ETH]"				<---//แก้แบบ manual
	//,"EncryptoTel [...":"EncryptoTel [WAVES]"
}
